
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 6.7
 PARAMETER PROC_INSTANCE = Cortex_M3_0
 PARAMETER sleep_timer = axi_timer_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_cortexm3
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Cortex_M3_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = axi_bram_ctrl_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = axi_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = axi_gpio_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_quad_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = ov_cmos_Image_Process_axi_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = contrast_hls_rom
 PARAMETER DRIVER_VER = 1.3
 PARAMETER HW_INSTANCE = ov_cmos_Image_Process_contrast_hls_rom_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = draw_line_hls
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = ov_cmos_Image_Process_draw_line_hls_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mask
 PARAMETER DRIVER_VER = 2.2
 PARAMETER HW_INSTANCE = ov_cmos_Image_Process_mask_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = projection1_hls
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = ov_cmos_Image_Process_projection1_hls_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = projection_mul_hls
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = ov_cmos_Image_Process_projection_mul_hls_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = resize_hls_axis
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = ov_cmos_Image_Process_resize_hls_axis_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = threshold2
 PARAMETER DRIVER_VER = 1.2
 PARAMETER HW_INSTANCE = ov_cmos_Image_Process_threshold2_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = ov_cmos_axi_gpio_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.4
 PARAMETER HW_INSTANCE = ov_cmos_axi_iic_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axivdma
 PARAMETER DRIVER_VER = 6.5
 PARAMETER HW_INSTANCE = ov_cmos_axi_vdma_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axivdma
 PARAMETER DRIVER_VER = 6.5
 PARAMETER HW_INSTANCE = ov_cmos_axi_vdma_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mig_7series
 PARAMETER DRIVER_VER = 2.1
 PARAMETER HW_INSTANCE = ov_cmos_mig_7series_0
END


