// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xthreshold2.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XThreshold2_CfgInitialize(XThreshold2 *InstancePtr, XThreshold2_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XThreshold2_SetRows(XThreshold2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XThreshold2_WriteReg(InstancePtr->Control_bus_BaseAddress, XTHRESHOLD2_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XThreshold2_GetRows(XThreshold2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XThreshold2_ReadReg(InstancePtr->Control_bus_BaseAddress, XTHRESHOLD2_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XThreshold2_SetCols(XThreshold2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XThreshold2_WriteReg(InstancePtr->Control_bus_BaseAddress, XTHRESHOLD2_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XThreshold2_GetCols(XThreshold2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XThreshold2_ReadReg(InstancePtr->Control_bus_BaseAddress, XTHRESHOLD2_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XThreshold2_SetMax_h(XThreshold2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XThreshold2_WriteReg(InstancePtr->Control_bus_BaseAddress, XTHRESHOLD2_CONTROL_BUS_ADDR_MAX_H_DATA, Data);
}

u32 XThreshold2_GetMax_h(XThreshold2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XThreshold2_ReadReg(InstancePtr->Control_bus_BaseAddress, XTHRESHOLD2_CONTROL_BUS_ADDR_MAX_H_DATA);
    return Data;
}

void XThreshold2_SetMin_h(XThreshold2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XThreshold2_WriteReg(InstancePtr->Control_bus_BaseAddress, XTHRESHOLD2_CONTROL_BUS_ADDR_MIN_H_DATA, Data);
}

u32 XThreshold2_GetMin_h(XThreshold2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XThreshold2_ReadReg(InstancePtr->Control_bus_BaseAddress, XTHRESHOLD2_CONTROL_BUS_ADDR_MIN_H_DATA);
    return Data;
}

