// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XTHRESHOLD2_H
#define XTHRESHOLD2_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xthreshold2_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XThreshold2_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XThreshold2;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XThreshold2_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XThreshold2_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XThreshold2_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XThreshold2_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XThreshold2_Initialize(XThreshold2 *InstancePtr, u16 DeviceId);
XThreshold2_Config* XThreshold2_LookupConfig(u16 DeviceId);
int XThreshold2_CfgInitialize(XThreshold2 *InstancePtr, XThreshold2_Config *ConfigPtr);
#else
int XThreshold2_Initialize(XThreshold2 *InstancePtr, const char* InstanceName);
int XThreshold2_Release(XThreshold2 *InstancePtr);
#endif


void XThreshold2_SetRows(XThreshold2 *InstancePtr, u32 Data);
u32 XThreshold2_GetRows(XThreshold2 *InstancePtr);
void XThreshold2_SetCols(XThreshold2 *InstancePtr, u32 Data);
u32 XThreshold2_GetCols(XThreshold2 *InstancePtr);
void XThreshold2_SetMax_h(XThreshold2 *InstancePtr, u32 Data);
u32 XThreshold2_GetMax_h(XThreshold2 *InstancePtr);
void XThreshold2_SetMin_h(XThreshold2 *InstancePtr, u32 Data);
u32 XThreshold2_GetMin_h(XThreshold2 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
